// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250710064322_addDataGamingRealted")]
    partial class addDataGamingRealted
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "High-performance laptops for gaming",
                            Name = "Gaming Laptops"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Keyboards, mice, and other accessories",
                            Name = "PC Accessories"
                        },
                        new
                        {
                            Id = 3,
                            Description = "High refresh rate and high resolution monitors",
                            Name = "Monitors"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "17-inch gaming laptop with RTX 3080",
                            Image = "alienware.jpg",
                            Name = "Alienware x17",
                            Price = 3000m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Slim and powerful gaming laptop",
                            Image = "rog.jpg",
                            Name = "ASUS ROG Zephyrus",
                            Price = 2500m,
                            Quantity = 8
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Desktop-class gaming performance",
                            Image = "msi.jpg",
                            Name = "MSI Raider GE76",
                            Price = 2800m,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Portable premium gaming laptop",
                            Image = "razer.jpg",
                            Name = "Razer Blade 15",
                            Price = 2700m,
                            Quantity = 7
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Mechanical gaming keyboard",
                            Image = "keyboard.jpg",
                            Name = "Logitech G Pro X Keyboard",
                            Price = 150m,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Lightweight gaming mouse",
                            Image = "mouse.jpg",
                            Name = "Logitech G Pro Wireless Mouse",
                            Price = 130m,
                            Quantity = 25
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "Gaming headset with 7.1 surround",
                            Image = "headset.jpg",
                            Name = "HyperX Cloud II",
                            Price = 100m,
                            Quantity = 18
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "Control panel for streamers",
                            Image = "streamdeck.jpg",
                            Name = "Elgato Stream Deck",
                            Price = 200m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "360Hz gaming monitor",
                            Image = "rogmonitor.jpg",
                            Name = "ASUS ROG Swift PG259QN",
                            Price = 700m,
                            Quantity = 6
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Description = "Curved QD-OLED monitor",
                            Image = "alienwaremonitor.jpg",
                            Name = "Dell Alienware AW3423DW",
                            Price = 1300m,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Description = "Super ultrawide gaming monitor",
                            Image = "odyssey.jpg",
                            Name = "Samsung Odyssey G9",
                            Price = 1500m,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Description = "4K UHD nano IPS gaming monitor",
                            Image = "lgmonitor.jpg",
                            Name = "LG UltraGear 27GN950",
                            Price = 800m,
                            Quantity = 5
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Product", b =>
                {
                    b.HasOne("WebApplication1.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebApplication1.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
