// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250709194354_addData")]
    partial class addData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "High-performance laptops for gaming on the go.",
                            ImageUrl = "https://images.unsplash.com/photo-1603791440384-56cd371ee9a7",
                            Name = "Gaming Laptops"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Essential accessories to enhance your gaming experience.",
                            ImageUrl = "https://images.unsplash.com/photo-1606813909357-6c06b3d06670",
                            Name = "Gaming Accessories"
                        },
                        new
                        {
                            Id = 3,
                            Description = "High-end parts to build or upgrade your gaming PC.",
                            ImageUrl = "https://images.unsplash.com/photo-1622445240093-5c583afad7df",
                            Name = "PC Components"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Ultra-thin, powerful gaming laptop with RTX graphics.",
                            ImageUrl = "https://images.unsplash.com/photo-1610465291908-9680af5dc5c3",
                            Name = "Alienware x15",
                            Price = 2500m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Compact gaming powerhouse with AMD Ryzen.",
                            ImageUrl = "https://images.unsplash.com/photo-1603791440384-56cd371ee9a7",
                            Name = "ASUS ROG Zephyrus G14",
                            Price = 1800m,
                            Quantity = 15
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Desktop-level performance in a portable chassis.",
                            ImageUrl = "https://images.unsplash.com/photo-1610484826969-6bfb495c7e7e",
                            Name = "MSI GE76 Raider",
                            Price = 2200m,
                            Quantity = 8
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Sleek design with powerful GPU for high FPS gaming.",
                            ImageUrl = "https://images.unsplash.com/photo-1609942531744-6aa46f8cc8f6",
                            Name = "Razer Blade 15",
                            Price = 2400m,
                            Quantity = 12
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Affordable yet powerful laptop for serious gamers.",
                            ImageUrl = "https://images.unsplash.com/photo-1622445240093-5c583afad7df",
                            Name = "Lenovo Legion 5 Pro",
                            Price = 1600m,
                            Quantity = 18
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Pro-level gaming headset with Blue VO!CE technology.",
                            ImageUrl = "https://images.unsplash.com/photo-1593642532973-d31b6557fa68",
                            Name = "Logitech G Pro X Headset",
                            Price = 130m,
                            Quantity = 25
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "Mechanical keyboard with customizable RGB and macro keys.",
                            ImageUrl = "https://images.unsplash.com/photo-1587202372775-989305e9b13f",
                            Name = "Corsair K95 RGB Keyboard",
                            Price = 200m,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "Ergonomic, ultra-fast gaming mouse.",
                            ImageUrl = "https://images.unsplash.com/photo-1579546928687-c5f301b01016",
                            Name = "Razer DeathAdder V2 Mouse",
                            Price = 70m,
                            Quantity = 40
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Description = "Large surface mouse pad for precise movements.",
                            ImageUrl = "https://images.unsplash.com/photo-1620332324517-917e03be63f4",
                            Name = "SteelSeries QcK Mouse Pad",
                            Price = 30m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Description = "Customizable control pad for streamers and content creators.",
                            ImageUrl = "https://images.unsplash.com/photo-1622445240093-5c583afad7df",
                            Name = "Elgato Stream Deck",
                            Price = 150m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Description = "Ultimate graphics card for 4K and high-FPS gaming.",
                            ImageUrl = "https://images.unsplash.com/photo-1625603614538-b3a9d66b3cb1",
                            Name = "NVIDIA RTX 4090 GPU",
                            Price = 1600m,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Description = "Top-tier processor for gaming and multitasking.",
                            ImageUrl = "https://images.unsplash.com/photo-1587206661871-8700cf32d296",
                            Name = "Intel Core i9-13900K CPU",
                            Price = 600m,
                            Quantity = 12
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Description = "High-speed DDR5 RAM for ultra-smooth gameplay.",
                            ImageUrl = "https://images.unsplash.com/photo-1611703376240-27f9f05ba6f6",
                            Name = "Corsair Vengeance 32GB RAM",
                            Price = 250m,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            Description = "Ultra-fast storage for quick loading and system performance.",
                            ImageUrl = "https://images.unsplash.com/photo-1616628182440-9fdf52e55b93",
                            Name = "Samsung 980 Pro 2TB SSD",
                            Price = 230m,
                            Quantity = 15
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Description = "Premium liquid cooling with customizable LCD display.",
                            ImageUrl = "https://images.unsplash.com/photo-1633081815765-1422eaa16c0b",
                            Name = "NZXT Kraken Z73 Liquid Cooler",
                            Price = 280m,
                            Quantity = 8
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Product", b =>
                {
                    b.HasOne("WebApplication1.Models.Category", null)
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApplication1.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
