// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250709141156_incertData")]
    partial class incertData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Electronic items",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Various books",
                            Name = "Books"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Apparel and accessories",
                            Name = "Clothing"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "High performance laptop",
                            Name = "Laptop",
                            Price = 1000m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Latest model smartphone",
                            Name = "Smartphone",
                            Price = 800m,
                            Quantity = 15
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Noise-cancelling headphones",
                            Name = "Headphones",
                            Price = 200m,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "10-inch display tablet",
                            Name = "Tablet",
                            Price = 400m,
                            Quantity = 12
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Waterproof smartwatch",
                            Name = "Smartwatch",
                            Price = 250m,
                            Quantity = 18
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Fiction novel",
                            Name = "Novel A",
                            Price = 20m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "Mystery novel",
                            Name = "Novel B",
                            Price = 18m,
                            Quantity = 40
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "Educational science book",
                            Name = "Science Book",
                            Price = 30m,
                            Quantity = 25
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Description = "Historical events book",
                            Name = "History Book",
                            Price = 25m,
                            Quantity = 35
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Description = "Famous person biography",
                            Name = "Biography",
                            Price = 28m,
                            Quantity = 30
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Description = "Cotton t-shirt",
                            Name = "T-Shirt",
                            Price = 15m,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Description = "Denim jeans",
                            Name = "Jeans",
                            Price = 40m,
                            Quantity = 60
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Description = "Winter jacket",
                            Name = "Jacket",
                            Price = 80m,
                            Quantity = 25
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            Description = "Comfortable sneakers",
                            Name = "Sneakers",
                            Price = 60m,
                            Quantity = 45
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Description = "Stylish cap",
                            Name = "Cap",
                            Price = 10m,
                            Quantity = 75
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Product", b =>
                {
                    b.HasOne("WebApplication1.Models.Category", null)
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApplication1.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
